apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sigstore-operator-bundle
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/sigstore-operator-bundle@sha256:aea3dd6429f12831531975db0df1b1bca7952abdcfa097dce56972f06d72712a
        name: container-image
        resources: {}
status: {}
