apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sigstore-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sigstore-operator-bundle
    app.kubernetes.io/part-of: operator-1-0-gamma
  name: sigstore-operator-bundle
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sigstore-operator-bundle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sigstore-operator-bundle
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/sigstore-operator-bundle@sha256:d94d0ae17c70d79fd9f333058fc1ec5b5d3dae9efebfdc283ca7a23f764b05b0
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
