apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sigstore-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sigstore-operator-bundle
    app.kubernetes.io/part-of: operator-1-0-gamma
  name: sigstore-operator-bundle
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sigstore-operator-bundle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sigstore-operator-bundle
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator-1-0-gamma/sigstore-operator-bundle@sha256:2f62912b1a46416eb6840b0f7801ea2ff2d51a74a9347eef125821faeb157006
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
